SELECT VA.NAME
FROM VOICE_ACTOR VA
         INNER JOIN CHARACTER CH ON VA.NAME = CH.VOICE_ACTOR
GROUP BY VA.NAME;

SELECT CH.NAME, VA.NAME
FROM CHARACTER CH
         INNER JOIN VOICE_ACTOR VA on CH.VOICE_ACTOR = VA.NAME
ORDER BY VA.NAME;

SELECT CH.NAME
FROM CHARACTER CH
         INNER JOIN VOICE_ACTOR VA on CH.VOICE_ACTOR = VA.NAME
GROUP BY VA.NAME, CH.NAME;

SELECT CH.id, CH.Name, CH.atk, CH.hp from CHARACTER CH
INNER JOIN VOICE_ACTOR VA on CH.VOICE_ACTOR = VA.NAME
GROUP BY CH.id, CH.Name, CH.atk, CH.hp HAVING MAX(CH.hp) > 16000;

SELECT name, class, illustrator, voice_actor
FROM CHARACTER WHERE name LIKE 'A%';

SELECT name, class, illustrator, voice_actor
FROM CHARACTER WHERE illustrator LIKE 'p__o';