CREATE SEQUENCE character_auto
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE va_auto
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE ce_auto
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE enemies_auto
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE class_auto
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE audit_auto
    INCREMENT BY 1
    START WITH 1;